### ISSUE TITLE
TUI doesn’t start anymore

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#87]
```
> ytcc tui
Traceback (most recent call last):
  File "/bin/ytcc", line 33, in <module>
    sys.exit(load_entry_point('ytcc==2.1.0', 'console_scripts', 'ytcc')())
  File "/usr/lib/python3.9/site-packages/ytcc/cli.py", line 567, in main
    cli.main(standalone_mode=False)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ytcc/cli.py", line 381, in tui
    Interactive(ytcc).run()
  File "/usr/lib/python3.9/site-packages/ytcc/tui.py", line 171, in run
    printer.print(selectable)
  File "/usr/lib/python3.9/site-packages/ytcc/printer.py", line 150, in print
    table = obj.table()
  File "/usr/lib/python3.9/site-packages/ytcc/tui.py", line 91, in table
    table = VideoPrintable(self.values()).table()
  File "/usr/lib/python3.9/site-packages/ytcc/printer.py", line 103, in table
    self._format_duration(video.duration),
  File "/usr/lib/python3.9/site-packages/ytcc/printer.py", line 77, in _format_duration
    return f"{duration // 60: 4.0f}:{duration % 60:02.0f}"
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

**Comment by EmRowlands** [comment]
Can you post the output of `ytcc bug-report`?

**Comment by woefe** [comment]
Might be related to https://github.com/ytdl-org/youtube-dl/issues/28049.
Mabye 0af64e0 fixes the issue. Can you try it?

**Comment by zoidby** [comment]
It does! Thank you very much. 

The speedy solutions here are impressive.

**Comment by woefe** [comment]
Cool! Thanks :smile: 

There won't be a bugfix release for this issue. The next release (2.2.0) will happen soon enough after #88 is merged.
